### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/openwrt-Pcap_DNSProxy#14]
- [x] add hotplug script
- [x] replace with dummy lists (to save space)
- [x] update to 0.4.6.5
- [x] move to procd init script
- [ ] upload bin to bintray
